package Kolekcje.mapy.zadanieStanowisko;

public enum Zadania {
    DOSTARCZANIE_PACZEK,
    KONTAKT_Z_KLIENTEM,
    SORTOWANIE_PACZEK,
    ROZWIĄZYWANIE_KONFLIKTOW,
    PRZYJMOWANIE_NOWYCH_PRACOWNIKOW,
    ODBIERANIE_PACZEK,
    LADOWANIE_SAMOCHODU
}
